name: CI/CD Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
          - os: macos-latest
            target: x86_64-apple-darwin
          - os: macos-latest
            target: aarch64-apple-darwin

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies for ARM builds (Ubuntu)
      if: matrix.os == 'ubuntu-latest' && matrix.target == 'aarch64-unknown-linux-gnu'
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-aarch64-linux-gnu libc6-dev-arm64-cross

    - name: Add Rust target
      run: rustup target add ${{ matrix.target }}

    - name: Build project
      run: |
        cargo build --release --target ${{ matrix.target }}
      env:
        CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER: aarch64-linux-gnu-gcc

    - name: Upload binary as artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.target }}-binary
        path: target/${{ matrix.target }}/release/*

  release:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v3
      with:
        path: ./artifacts

    - name: Set up Git Identity
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

    - name: Save New Tag to Environment
      id: tag-info
      run: |
        git fetch --tags
        DATE=$(date +"%Y%m%d")
        EXISTING_TAGS=$(git tag | grep "^${DATE}" || true)

        if [ -z "$EXISTING_TAGS" ]; then
            NEW_TAG="${DATE}-1"
        else
            MAX_INCREMENT=$(echo "$EXISTING_TAGS" | awk -F '-' '{print $2}' | sort -nr | head -n1 || echo "0")
            NEW_INCREMENT=$((MAX_INCREMENT + 1))
            NEW_TAG="${DATE}-${NEW_INCREMENT}"
        fi

        echo "NEW_TAG=$NEW_TAG" >> $GITHUB_ENV
        echo "Created tag: $NEW_TAG"

    - name: Create and Push Tag
      run: |
        NEW_TAG=${{ env.NEW_TAG }}
        git tag -a "$NEW_TAG" -m "Release $NEW_TAG"
        git push origin "$NEW_TAG"

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ env.NEW_TAG }}
        files: ./artifacts/**
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
