name: CI/CD Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: x86_64-unknown-linux-gnu
        profile: minimal

    - name: Build project
      run: |
        cargo build --release

    - name: Run tests
      run: |
        cargo test

    - name: Upload binary as artifact
      uses: actions/upload-artifact@v3
      with:
        name: rosetta_file_linker
        path: target/release/rosetta_file_linker

  release:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: x86_64-unknown-linux-gnu
        profile: minimal

    - name: Build project
      run: |
        cargo build --release

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: target/release/rosetta_file_linker
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  tag-release:
    runs-on: ubuntu-latest
    needs: release

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

    - name: Generate and push tags
      run: |
        # Get the current date in yyyymmdd format
        DATE=$(date +"%Y%m%d")

        # Check for existing tags with today's date and increment
        EXISTING_TAGS=$(git tag | grep "^${DATE}")
        if [ -z "$EXISTING_TAGS" ]; then
            NEW_TAG="${DATE}-1"
        else
            MAX_INCREMENT=$(echo "$EXISTING_TAGS" | awk -F '-' '{print $2}' | sort -nr | head -n1)
            NEW_INCREMENT=$((MAX_INCREMENT + 1))
            NEW_TAG="${DATE}-${NEW_INCREMENT}"
        fi

        # Create the new tag
        git tag -a "$NEW_TAG" -m "Release for $NEW_TAG"
        echo "Created tag: $NEW_TAG"

        # Update the 'latest' tag to point to the new release
        git tag -f latest
        echo "Updated 'latest' tag to point to $NEW_TAG"

        # Push tags to the remote repository
        git push origin "$NEW_TAG"
        git push origin -f latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
