name: Rust CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: x86_64-unknown-linux-gnu
        profile: minimal

    - name: Build project
      run: |
        cargo build --release

    - name: Run tests
      run: |
        cargo test

    - name: Upload binary as artifact
      uses: actions/upload-artifact@v3
      with:
        name: rosetta_file_linker
        path: target/release/rosetta_file_linker

  release:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: x86_64-unknown-linux-gnu
        profile: minimal

    - name: Build project
      run: |
        cargo build --release

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: target/release/rosetta_file_linker
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
