name: Tag Release

on:
  push:
    branches:
      - main

jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Generate and push tags
        run: |
          chmod +x scripts/create_tag.sh
          ./scripts/create_tag.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
